// @ts-check

// 这在 Node.js 中运行 - 不要在此处使用客户端代码（浏览器 API、JSX...）

/**
 * 创建侧边栏使您能够：
 * - 创建有序的文档组
 * - 为该组的每个文档呈现侧边栏
 * - 提供上一页/下一页导航

 * 侧边栏可以从文件系统生成，也可以在此明确定义。

 * 创建任意数量的侧边栏。

 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认情况下，Docusaurus 从 docs 文件夹结构生成侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 但您也可以手动创建侧边栏
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: '教程',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
