// @ts-check

const sidebars = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro', label: '简介' },
    { type: 'doc', id: '配置说明', label: '配置说明' },
    { type: 'autogenerated', dirName: 'tutorial-basics' },
    { type: 'autogenerated', dirName: 'tutorial-extras' },
  ],
  macSidebar: [
    {
      type: 'category',
      label: '目录111',
      collapsed: false,
      link: { type: 'generated-index', title: '目录111', description: '目录111下的文档' },
      items: [
        { type: 'doc', id: 'mac/目录111/ghostty' },
        { type: 'doc', id: 'mac/目录111/intro' },
      ],
    },
    {
      type: 'category',
      label: '目录222',
      collapsed: false,
      link: { type: 'generated-index', title: '目录222', description: '目录222下的文档' },
      items: [
        { type: 'doc', id: 'mac/目录222/intro' },
      ],
    },
  ],
  ubuntuSidebar: [
    {
      type: 'category',
      label: '目录2',
      collapsed: false,
      link: { type: 'generated-index', title: '目录2', description: '目录2下的文档' },
      items: [
        { type: 'doc', id: 'ubuntu/目录2/cmd' },
        { type: 'doc', id: 'ubuntu/目录2/intro' },
      ],
    },
    {
      type: 'category',
      label: '目录3',
      collapsed: false,
      link: { type: 'generated-index', title: '目录3', description: '目录3下的文档' },
      items: [
        { type: 'doc', id: 'ubuntu/目录3/intro' },
      ],
    },
  ],
  toolSidebar: [
  {
    type: 'category',
    label: 'NewTab',
    collapsed: false,
    link: { type: 'generated-index', title: '工具', description: '开发工具' },
    items: [
      { type: 'doc', id: 'tool/NewTab/clone' },
      { type: 'doc', id: 'tool/NewTab/wiki' },
    ],
  },
],
};

export default sidebars;
